CREATE DATABASES IF NOT EXISTS liquid_swaps;

CREATE TABLE swaps (
id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
post_date TIMESTAMP,
base_cur VARCHAR(30) NOT NULL,
base_amt FLOAT NOT NULL,
sec_cur VARCHAR(30) NOT NULL,
sec_amt FLOAT NOT NULL,
proposal MEDIUMTEXT NOT NULL,
auth_code MEDIUMTEXT NOT NULL
);

CREATE TABLE accepted (
id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
post_date TIMESTAMP,
swap_id INT NOT NULL,
acceptance MEDIUMTEXT NOT NULL
);